spring:
  datasource:
    url: jdbc:mysql://db:3306/healthcheck?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: cache
      port: 6379

  kafka:
    bootstrap-servers: broker:9092